name: Build CI (updated action)

on: workflow_dispatch

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v4
      with:
        submodules: true
    - name: Set up JDK 21 (Temurin - latest LTS)
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'
    - name: Build with Gradle (debug version)
      run: ./gradlew assembleDebug lintVitalRelease
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: material_files-debug.apk
        path: app/build/outputs/apk/debug/app-debug.apk
        retention-days: 90
        compression-level: 9
